### ISSUE TITLE
前辈您好，请问出现以下如图情况是登录不成功吗？应当如何解决？

### ISSUE THREAD

**Issue by TsuyuriKanawo** [IshiKura-a/Quicker#2]
![image](https://user-images.githubusercontent.com/56284089/163998506-7a456702-bd81-410b-84df-5d4be0491115.png)

**Comment by IshiKura-a** [comment]
有两个同伴？检查第三个同伴的账号密码是否正确

**Comment by TsuyuriKanawo** [comment]
.json文件里buddies是指同伴的账号密码信息？是指同伴码还是表单里确实需要密码

**Comment by IshiKura-a** [comment]
同伴码会刷新，所以用的是伙伴的账号密码直接获取同伴码

**Comment by TsuyuriKanawo** [comment]
原来如此~我按照正确的改了之后好像输出了一些奇怪的语句（捂脸），小白看不懂，麻烦大佬帮我看一下下
![image](https://user-images.githubusercontent.com/56284089/164011255-c151867d-a423-4287-830e-4066238638a2.png)

**Comment by IshiKura-a** [comment]
还是账号的问题，建议自查一下第三个账号

**Comment by TsuyuriKanawo** [comment]
我现在只用了自己的和一个同伴的账号，是只要填两个内容吗？
![image](https://user-images.githubusercontent.com/56284089/164018639-98da6f93-d546-4dc4-818e-ff4e0c61ea7b.png)

**Comment by IshiKura-a** [comment]
哦，现在版本的样例是以两个同伴为例的，只需要填一个就好了，另一个删掉就好，你可以了解一下json格式

**Comment by TsuyuriKanawo** [comment]
![image](https://user-images.githubusercontent.com/56284089/164038188-189241f2-7108-4f94-8afa-7fe40d0da545.png)
前一个格式错误可能跟json文件里的内容有关？

**Comment by IshiKura-a** [comment]
第一个错误，可能是json没有写成数组，直接给了一个对象

**Comment by TsuyuriKanawo** [comment]
对，但是加了中括号就会报之前那个错误

**Comment by IshiKura-a** [comment]
对照此输出：
![image](https://user-images.githubusercontent.com/51883990/164047947-e065659c-5cf0-4acf-a55c-baee109e4bca.png)
我认为还是同伴码方面的问题，你需要：
1. 确保config.json为如下内容，
```json
{
  "username": "aaa",
  "password": "bbb",
  "buddies": [
    {
      "username": "ccc",
      "password": "ddd"
    }
  ]
}
```
2. 确认同伴可以用此账号和密码获取同伴码

**Comment by TsuyuriKanawo** [comment]
你好，自查了一下，发现是没有用最新的代码所致...现尝试已经可以运行啦！不过当预约场数为2的时候会预约失败，请问前辈需要注意什么吗？

**Comment by IshiKura-a** [comment]
预约场次2失败是因为zdty不允许预约两场（

**Comment by TsuyuriKanawo** [comment]
感谢！
