### ISSUE TITLE
现在新增验证码模块了，大佬有考虑过使用OCR绕过吗

### ISSUE THREAD

**Issue by TinyTigerPan** [IshiKura-a/Quicker#5]
浙大体艺现在在预约场地之时需要输入点击文字的验证码。如下图。
<img width="558" alt="image" src="https://user-images.githubusercontent.com/32625100/232990829-9821ebde-4aa6-40a6-95b4-be013133a7e9.png">

[ddddocr](https://github.com/sml2h3/ddddocr)貌似可以自动的识别该类型验证码，大佬有没有考虑集成该功能。

**Comment by IshiKura-a** [comment]
有空研究一下，最近科研比较忙，如果有pr的话可以提交我检查后合并。

**Comment by TinyTigerPan** [comment]
OCR部分我已经完成了
```python
import ddddocr
import cv2
import base64
from io import BytesIO
import numpy as np

def ocr_decode(base64_img):
    decode_dict = {}
    det = ddddocr.DdddOcr(det=True)
    ocr = ddddocr.DdddOcr(beta=True)

    image_data = base64.b64decode(base64_img)
    stream = BytesIO(image_data)
    image_bytes = stream.read()

    poses = det.detection(image_bytes)

    nparr = np.frombuffer(image_data, np.uint8)
    im = cv2.imdecode(nparr, cv2.IMREAD_COLOR)

    for box in poses:
        x1, y1, x2, y2 = box
        cropped_img = im[y1:y2, x1:x2]
        cv2.imwrite("cropped.jpg", cropped_img)
        with open("cropped.jpg", 'rb') as f:
            cropped_img = f.read()
        res = ocr.classification(cropped_img)
        decode_dict[res] = box
    return decode_dict
```
传入图片的base64编码字符串，就能获取字符的位置
<img width="309" alt="image" src="https://user-images.githubusercontent.com/32625100/233013541-c2bb73d7-ac36-4273-a886-979f8d8e3aa6.png">
```
print(ocr_decode(base64_img))
{'而': [200, 47, 236, 81], '说': [79, 10, 112, 41], '见': [14, 66, 47, 96], '睛': [170, 65, 199, 92]}
```
但是后面的发送请求我不是特别擅长，应该还涉及到js前端等技术，大佬有空可以看看。

**Comment by IshiKura-a** [comment]
简单摸排了一下流程，目前问题在于，他对点击序列坐标做了一个编码（加密），需要研究一下编码方法，其他都很简单。

**Comment by WuTao-CS** [comment]
如果是这段代码进行的编码位置的话：
![secretKey](https://user-images.githubusercontent.com/48761159/233044621-b2560aa7-a52c-4448-925e-c1a2b575f83d.png)
加密编码算法可能在这里（纯小白 不太确定）：
![encode](https://user-images.githubusercontent.com/48761159/233044674-e940e1b3-e1ff-4c3f-b6ef-44f4608cfd7f.png)

**Comment by IshiKura-a** [comment]
应该是的

**Comment by IshiKura-a** [comment]
上面那个ocr库不行，需要换一个效果强一点的

**Comment by IshiKura-a** [comment]
已实现
